name: Second Workflow test by Zain
run-name: ${{ github.actor}} has triggeed this workflow using ${{ github.event}} on ${{ github.repository}} and on branch ${{ github.ref_name}}.
on: [push,pull_request,workflow_dispatch]
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checking out repository
        uses: actions/checkout@v4
      - name: Printing a file
        run: cat firstfile.txt
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a greetings message
        run: echo "Welcome to the hell of Devops"
